CREATE TABLE IF NOT EXISTS data (
  ID INT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS data (
  ID INT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL
);
